/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "host": {                                        "en": "Hostname / IP Address",                           "de": "Hostname / IP-Adresse",                           "ru": "Имя хоста / IP-адрес",                            "pt": "Nome do host / endereço IP",                      "nl": "Hostnaam / IP-adres",                             "fr": "Nom d'hôte / adresse IP",                         "it": "Nome host / indirizzo IP",                        "es": "Nombre de host / dirección IP",                   "pl": "Nazwa hosta / adres IP",                          "zh-cn": "主机名/ IP地址"},
    "luxPort": {                                     "en": "Luxtronik Port",                                  "de": "Luxtronik Port",                                  "ru": "Luxtronik порт",                                  "pt": "Porto Luxtronik",                                 "nl": "Luxtronik-poort",                                 "fr": "Port Luxtronik",                                  "it": "Porto Luxtronik",                                 "es": "Puerto Luxtronik",                                "pl": "Luxtronik Port",                                  "zh-cn": "Luxtronik港口"},
    "luxtronik2 adapter settings": {                 "en": "Adapter settings for luxtronik2",                 "de": "Adaptereinstellungen für Luxtronik2",             "ru": "Настройки адаптера для luxtronik2",               "pt": "Configurações do adaptador para luxtronik2",      "nl": "Adapterinstellingen voor luxtronik2",             "fr": "Paramètres d'adaptateur pour Luxtronik2",         "it": "Impostazioni dell'adattatore per luxtronik2",     "es": "Ajustes del adaptador para luxtronik2",           "pl": "Ustawienia adaptera dla luxtronik2",              "zh-cn": "luxtronik2的适配器设置"},
    "password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "port": {                                        "en": "WebSocket Port",                                  "de": "WebSocket-Port",                                  "ru": "Порт WebSocket",                                  "pt": "Porta WebSocket",                                 "nl": "WebSocket-poort",                                 "fr": "Port WebSocket",                                  "it": "Porta WebSocket",                                 "es": "Puerto WebSocket",                                "pl": "Port WebSocket",                                  "zh-cn": "WebSocket端口"},
    "refreshInterval": {                             "en": "Refresh Interval",                                "de": "Aktualisierungsintervall",                        "ru": "Интервал обновления",                             "pt": "Intervalo de atualização",                        "nl": "Vernieuwingsinterval",                            "fr": "Intervalle de rafraîchissement",                  "it": "Intervallo di aggiornamento",                     "es": "Intervalo de actualización",                      "pl": "Częstotliwość odświeżania",                       "zh-cn": "刷新间隔"},
    "seconds": {                                     "en": "seconds",                                         "de": "Sekunden",                                        "ru": "секунд",                                          "pt": "segundos",                                        "nl": "seconden",                                        "fr": "secondes",                                        "it": "secondi",                                         "es": "segundos",                                        "pl": "sekundy",                                         "zh-cn": "秒"},
};